use serde::{Deserialize, Serialize};
use serde_json::Value;
use zylcode_mcp::real_tools::{ToolSchema, RiskLevel};

/// Structured decision from the agent model
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "action", content = "payload")]
pub enum AgentDecision {
    /// Model is thinking/reasoning
    Think {
        thought: String,
    },
    
    /// Model is generating a plan
    Plan {
        steps: Vec<PlanStep>,
    },
    
    /// Model wants to execute a tool
    ToolCall {
        tool_id: String,
        arguments: Value,
        reason: String,
        expected_result: Option<String>,
    },
    
    /// Model requests user approval
    RequestApproval {
        action_description: String,
        risk_level: RiskLevel,
        tool_id: Option<String>,
    },
    
    /// Model wants to verify results
    Verify {
        checks: Vec<String>,
    },
    
    /// Model declares task complete
    Complete {
        summary: String,
        evidence: Vec<String>,
        remaining_limitations: Vec<String>,
    },
    
    /// Model declares task failed
    Fail {
        reason: String,
        error: String,
        repair_suggestions: Vec<String>,
    },
}

/// Plan step generated by the model
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanStep {
    pub id: String,
    pub description: String,
    pub expected_files: Vec<String>,
    pub expected_tools: Vec<String>,
    pub risk: RiskLevel,
    pub verification: String,
}

/// Context provided to the model
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentContext {
    pub workspace_root: String,
    pub file_tree: Vec<String>,
    pub relevant_files: Vec<String>,
    pub user_goal: String,
    pub recent_tool_results: Vec<Value>,
    pub current_plan: Option<Vec<PlanStep>>,
    pub current_state: String,
    pub git_status: Option<String>,
    pub errors: Vec<String>,
}

/// Result of tool execution returned to model
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolObservation {
    pub tool_id: String,
    pub success: bool,
    pub stdout: Option<String>,
    pub stderr: Option<String>,
    pub exit_code: Option<i32>,
    pub changed_files: Vec<String>,
    pub diagnostics: Vec<String>,
    pub evidence_id: String,
}

/// Approval decision
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ApprovalDecision {
    Approved,
    Denied { reason: String },
    Modified { new_arguments: Value },
}

/// Provider capability request
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CapabilityRequest {
    pub reasoning: bool,
    pub coding: bool,
    pub tool_use: bool,
    pub vision: bool,
    pub context_size: usize,
}

impl Default for CapabilityRequest {
    fn default() -> Self {
        Self {
            reasoning: true,
            coding: true,
            tool_use: true,
            vision: false,
            context_size: 4096,
        }
    }
}